# Generated by Django 4.2.6 on 2023-10-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reclamation', models.IntegerField()),
                ('panne_annoncee', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Checklist_station',
        ),
    ]
