# Generated by Django 4.2.6 on 2023-10-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0003_checklist_stat_accident_circulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='categorie_reclamation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
