# Generated by Django 4.2.6 on 2023-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0004_alter_checklist_stat_categorie_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='entreprise_intervenante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='localite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
