# Generated by Django 4.2.6 on 2023-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0005_alter_checklist_stat_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='date_reclamation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='echeance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
