# Generated by Django 4.2.6 on 2023-10-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0006_alter_checklist_stat_date_reclamation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='arret_activite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='autre_lesion1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='autre_nature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='autre_travaux',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='date_diagnostic',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='fonction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='interlocuteur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='livraison_carburant',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='panne_reel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='presence_zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
