# Generated by Django 4.2.6 on 2023-10-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0007_alter_checklist_stat_arret_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='livraison_carburant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_stat',
            name='port_EPI',
            field=models.BooleanField(default=False),
        ),
    ]
