# Generated by Django 4.2.6 on 2023-10-17 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0008_alter_checklist_stat_livraison_carburant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='livraison_carburant',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
