# Generated by Django 4.2.6 on 2023-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0009_alter_checklist_stat_livraison_carburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_stat',
            name='panne_annoncee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
