# Generated by Django 4.2.6 on 2023-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0013_checklist_permis_feu_prest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='autre_document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='autre_materiel_utilise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='autre_risque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='autre_type_travaux',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='bache',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='balisage_perimetre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='consignation_equipement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='degazage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='demontage_tuyauterie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='descriptif_travail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='ecran',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='entreprise_intervenante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='evacuation_substance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='extincteur',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='intervenant1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='intervenant2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='intervenant3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='intervenant4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='isolation_tuyauterie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='localite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='protection_element',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='sable',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='teneur_LIE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='teneur_oxygene',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='test_atmospherique',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='ventilation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='vidange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
