# Generated by Django 4.2.6 on 2023-10-17 20:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0014_alter_checklist_permis_feu_prest_autre_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='heure_debut',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='heure_fin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
