# Generated by Django 4.2.6 on 2023-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0015_alter_checklist_permis_feu_prest_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_entete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
