# Generated by Django 4.2.6 on 2023-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0016_alter_checklist_permis_feu_prest_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='permis_feu_delivre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
