# Generated by Django 4.2.6 on 2023-10-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0017_alter_checklist_permis_feu_prest_heure_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='checklist_permis_feu_prest',
            name='heure_fin',
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
