# Generated by Django 4.2.6 on 2023-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0018_remove_checklist_permis_feu_prest_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist_permis_feu_prest',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='heure_debut_surveillance',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist_permis_feu_prest',
            name='heure_fin_surveillance',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
