# Generated by Django 4.2.6 on 2023-10-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovena', '0019_checklist_permis_feu_prest_heure_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist_excavation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entete', models.DateField(default=datetime.date.today)),
                ('Registre_entete', models.IntegerField()),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('entreprise_intervenante', models.CharField(max_length=100)),
                ('descriptif', models.CharField(blank=True, max_length=500, null=True)),
                ('profondeur_excavation', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('type_excavation', models.CharField(blank=True, max_length=10, null=True)),
                ('dessin1', models.CharField(blank=True, max_length=50, null=True)),
                ('dessin2', models.CharField(blank=True, max_length=50, null=True)),
                ('dessin3', models.CharField(blank=True, max_length=50, null=True)),
                ('dessin4', models.CharField(blank=True, max_length=50, null=True)),
                ('eau_incendie', models.BooleanField(default=False)),
                ('eau_pluviale', models.BooleanField(default=False)),
                ('eau_riviere', models.BooleanField(default=False)),
                ('effluent', models.BooleanField(default=False)),
                ('eau_domestique', models.BooleanField(default=False)),
                ('sanitaire', models.BooleanField(default=False)),
                ('cable_communication', models.BooleanField(default=False)),
                ('mise_terre', models.BooleanField(default=False)),
                ('structure_adjacente', models.BooleanField(default=False)),
                ('cable_cathodique', models.BooleanField(default=False)),
                ('ligne_gaz', models.BooleanField(default=False)),
                ('atre_obstruction', models.BooleanField(default=False)),
                ('electrique_11kv', models.BooleanField(default=False)),
                ('electrique_6kv', models.BooleanField(default=False)),
                ('electrique_690v', models.BooleanField(default=False)),
                ('electrique_690i', models.BooleanField(default=False)),
                ('commentaire_obstruction1', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire_obstruction2', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire_obstruction3', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire_obstruction4', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire_obstruction5', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire_obstruction6', models.CharField(blank=True, max_length=50, null=True)),
                ('pente', models.BooleanField(default=False)),
                ('banc', models.BooleanField(default=False)),
                ('etayage', models.BooleanField(default=False)),
                ('pretection_nuit', models.BooleanField(default=False)),
                ('pretection_ouverture', models.BooleanField(default=False)),
                ('permis_espace', models.BooleanField(default=False)),
                ('pompage_eau', models.BooleanField(default=False)),
                ('fermeture_route', models.BooleanField(default=False)),
                ('mesure_securite_additionnel', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire1', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire2', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire3', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire4', models.CharField(blank=True, max_length=50, null=True)),
                ('effectuee', models.BooleanField(default=False)),
                ('effectuer_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('effectuer_date', models.DateField(default=datetime.date.today)),
                ('representant_contracant', models.BooleanField(default=False)),
                ('representant_contracant_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('representant_contracant_date', models.DateField(default=datetime.date.today)),
                ('superviseur_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('superviseur_date', models.DateField(default=datetime.date.today)),
                ('representant_proprietaire_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('representant_proprietaire_date', models.DateField(default=datetime.date.today)),
                ('superviseur_excavation_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('superviseur_excavation_date', models.DateField(default=datetime.date.today)),
                ('date_achevement_excavation', models.DateField(default=datetime.date.today)),
                ('permis_excavation_delivre', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='aout',
        ),
        migrations.DeleteModel(
            name='avril',
        ),
        migrations.DeleteModel(
            name='decembre',
        ),
        migrations.DeleteModel(
            name='fevrier',
        ),
        migrations.DeleteModel(
            name='juillet',
        ),
        migrations.DeleteModel(
            name='juin',
        ),
        migrations.DeleteModel(
            name='mai',
        ),
        migrations.DeleteModel(
            name='mars',
        ),
        migrations.DeleteModel(
            name='novembre',
        ),
        migrations.DeleteModel(
            name='octobre',
        ),
        migrations.DeleteModel(
            name='septembre',
        ),
    ]
